name: Continuous Deployment (CD)

on:
    workflow_dispatch:
    push:
      branches: [ "**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          make init

      - name: Build Wheel file
        run: |
          make build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Upload to S3
        run: |
            make upload

      - name: SSH into EC2, Downloading from S3 and Deploy Project
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            port: 22
            script: |
              sudo apt update
              
              aws s3 cp s3://project-sum-two-numbers-wheels/path/project_sum_two_numbers-0.1.0-py3-none-any.whl ./project_sum_two_numbers.whl    
              
              echo "Creating Dockerfile"
              cat <<EOL > Dockerfile
              FROM python:3.10
              WORKDIR /app-sum-two-numbers
              COPY ./project_sum_two_numbers.whl /app/project_sum_two_numbers.whl
              RUN pip install /app-sum-two-numbers/project_sum_two_numbers.whl
              CMD ["python3", "-c", "from project_sum_two_numbers import get_user_input, sum_of_two_numbers; print('Setup complete')"]
              EOL
    
              docker build -t project_sum_two_numbers .
    
              docker rm -f project_sum_two_numbers || true
    
              docker run -d --name project_sum_two_numbers project_sum_two_numbers
