name: Continuous Deployment (CD)

on:
    workflow_dispatch:
    push:
      branches: [ "**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          make init

      - name: Build Wheel file
        run: |
          make build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
            make upload
                
      - name: Execute application via SSH on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            port: 22
            script: |
              aws s3 cp s3://project-sum-two-numbers-wheels/project_sum_two_numbers-0.1.0-py3-none-any.whl ./project_sum_two_numbers-0.1.0-py3-none-any.whl
              rm -f -r ./.venv
              python3 -m venv venv
              source venv/bin/activate
              pip3 install --force-reinstall ./project_sum_two_numbers-0.1.0-py3-none-any.whl
              sum_two_numbers
