name: Continuous Deployment (CD)

on:
    push:
      branches: [ "**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          make init

      - name: Build Wheel file
        run: |
          make build
