name: Continuous Integration (CI)

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          make init

      - name: Run code style checks
        run: make codestyle

      - name: Run tests and generate coverage
        run: make test
      
#      - name: Run SonarQube analysis using Docker
#        env:
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: |
#          docker run --rm \
#            -e SONAR_HOST_URL=$SONAR_HOST_URL \
#            -e SONAR_TOKEN=$SONAR_TOKEN \
#            -v $(pwd):/usr/src \
#            sonarsource/sonar-scanner-cli \
#            sonar-scanner

