name: Python Linter

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow when a pull request is made to the 'main' branch

jobs:
  lint:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual machine to run the job

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the version of Python to use

      # Step 3: Install required dependencies (linters)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install pylint  # Install linter: pylint

      # Step 4: Run Pylint to check code quality and logic issues
      - name: Run Pylint
        run: pylint **/*.py  # Analyze all Python files in the repository